--- #YAML:1.0
name: iCal-Parser-HTML
version: 1.06
author:
  - Rick Frankel, cpan@rickster.com
abstract: Generate HTML calendars from iCalendars
license: perl
requires:
  XML::LibXML: 1.58
  XML::LibXSLT: 1.57
  iCal::Parser::SAX: 1.05
build_requires:
  Test::More: 0.47
provides:
  iCal::Parser::HTML:
    file: lib/iCal/Parser/HTML.pm
    version: 1.06
generated_by: Module::Build version 0.2606
